/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this temp file, choose Tools | Templates
 * and open the temp in the editor.
 */
package User_Interface;

import Error_Logs.PathConfig;

import static Image_Process.ImageProcess.LeftCheek;
import static Image_Process.ImageProcess.RightCheek;
import static Image_Process.SkinColour.SkinCol;
import Neural_Network.NuralN;
import static Neural_Network.NuralN.trainNet;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import weka.classifiers.Evaluation;
import weka.classifiers.lazy.IBk;
import weka.core.Instance;
import weka.core.Instances;
import java.awt.event.*;
import java.awt.image.*;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.*;

/**
 *
 * @author SC
 */
public class SmartSkinCare extends javax.swing.JFrame {

    public static PathConfig I_PATH = new PathConfig();
    public static String MainPath = (I_PATH.GetPaths("PImage"));

    String filename = null;
    
    public static JTextArea jt;

    /**
     * Creates new form SmartSkinCare
     */
    public SmartSkinCare() {
        initComponents();
        trainNet();
        RCButton.setOpaque(false);
        RCButton.setContentAreaFilled(false);
        LCButton.setOpaque(false);
        LCButton.setContentAreaFilled(false);

        RCButton.hide();
        LCButton.hide();
        jt = this.jTextArea1;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        LCButton = new javax.swing.JButton();
        RCButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        SkinColorjLabel = new javax.swing.JLabel();
        Result_Panel = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        HelpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LCButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        LCButton.setOpaque(false);
        LCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LCButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(LCButton);
        LCButton.setBounds(40, 280, 180, 210);

        RCButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));
        RCButton.setOpaque(false);
        RCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(RCButton);
        RCButton.setBounds(430, 280, 170, 210);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabel1.setMaximumSize(new java.awt.Dimension(625, 625));
        jLabel1.setMinimumSize(new java.awt.Dimension(625, 625));
        jLabel1.setPreferredSize(new java.awt.Dimension(625, 625));
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(10, 10, 625, 650);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jButton1.setText("Select Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SkinColorjLabel.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        SkinColorjLabel.setForeground(new java.awt.Color(51, 51, 255));
        SkinColorjLabel.setText("Analysis Results:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        Result_Panel.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Result_Panel)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SkinColorjLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SkinColorjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Result_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel1);
        jPanel1.setBounds(650, 10, 430, 340);

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Smart Skin Care");

        HelpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Interface/1472743359_Info.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 79, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void SColor(String Color) {

        String LL = Color;

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File f = fc.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(filename);
        Image image = imageIcon.getImage();
        Image newimg = image.getScaledInstance(650, 625, java.awt.Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(newimg);
        jLabel1.setIcon(imageIcon);
        RCButton.show();
        LCButton.show();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void RCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCButtonActionPerformed
        try {
            RightCheek(filename);
            ImageIcon imageIcon = new ImageIcon(MainPath + "RightCheek.jpg");
            Image image = imageIcon.getImage();
            Image newimg = image.getScaledInstance(650, 625, java.awt.Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(newimg);
            jLabel1.setIcon(imageIcon);
            SkinCol(MainPath + "RightCheek.jpg");
            RCButton.hide();
            LCButton.hide();
        } catch (Exception ex) {
            Logger.getLogger(SmartSkinCare.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RCButtonActionPerformed

    private void LCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LCButtonActionPerformed

        try {
            LeftCheek(filename);
            ImageIcon imageIcon = new ImageIcon(MainPath + "LeftCheek.jpg");
            Image image = imageIcon.getImage();
            Image newimg = image.getScaledInstance(650, 625, java.awt.Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(newimg);
            jLabel1.setIcon(imageIcon);
            SkinCol(MainPath + "LeftCheek.jpg");
            RCButton.hide();
            LCButton.hide();
        } catch (Exception ex) {
            Logger.getLogger(SmartSkinCare.class.getName()).log(Level.SEVERE, null, ex);
        } // TODO add your handling code here:
    }//GEN-LAST:event_LCButtonActionPerformed

  

    
 ////////////////////////////////////////////////////////////////////////

    public static void DetectDisease(String[] numberArray) {

        ArrayList<Double> results = NuralN.predictDisease(numberArray);

        

        double LastResult = (results.get(results.size() - 1));
        String aString = Double.toString(LastResult);
        String dCode = (int) LastResult + "";

        HashMap<String, String> tInfo = DB_Con.DBConnection
                .getInstance()
                .treatment(dCode);
        String displayMessage = "";
        
        displayMessage = "Disease Name : " + tInfo.get("name")
                +" \nCause : " + tInfo.get("cause")
                +" \nTreatment : " + tInfo.get("treatments");
        jt.setText(displayMessage);
        

        System.out.println("De : " + aString.substring(0, 1));
        

    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartSkinCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartSkinCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartSkinCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartSkinCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartSkinCare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HelpButton;
    private javax.swing.JButton LCButton;
    private javax.swing.JButton RCButton;
    private javax.swing.JScrollPane Result_Panel;
    private javax.swing.JLabel SkinColorjLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables



}
